import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import './LandingPage.css';

const LandingPage = () => {
  const navigate = useNavigate();
  const [scrolled, setScrolled] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      setScrolled(window.scrollY > 50);
    };
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const teamMembers = [
    {
      name: 'Poonam',
      role: 'Developer',
      image: '/team/poonam.jpg'
    },
    {
      name: 'Preeti',
      role: 'Developer',
      image: '/team/preeti.png'
    },
    {
      name: 'Rohit',
      role: 'Developer',
      image: '/team/rohit.jpg'
    },
    {
      name: 'Tamanna',
      role: 'Developer',
      image: '/team/tamanna.jpg'
    }
  ];

  const features = [
    {
      icon: '🎯',
      title: 'AI-Powered Stories',
      description: 'Learn DSA concepts through engaging, personalized stories generated by advanced AI'
    },
    {
      icon: '🎨',
      title: 'Interactive Visualizations',
      description: 'See algorithms come to life with dynamic, animated visualizations'
    },
    {
      icon: '🎮',
      title: 'Gamified Learning',
      description: 'Take quizzes, earn achievements, and track your progress'
    },
    {
      icon: '🌈',
      title: 'Multiple Themes',
      description: 'Choose from fantasy, sci-fi, detective, and more learning themes'
    }
  ];

  return (
    <div className="landing-page">
      {/* Navigation */}
      <nav className={`landing-nav ${scrolled ? 'scrolled' : ''}`}>
        <div className="nav-container">
          <div 
            className="nav-logo" 
            onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
            style={{ cursor: 'pointer' }}
          >
            <img src="/ok.png" alt="DSA Logo" className="nav-logo-img" />
            <span className="logo-text">DSA Storyteller</span>
          </div>
          <button className="nav-login-btn" onClick={() => navigate('/login')}>
            Login
          </button>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="hero-section">
        <div className="hero-background"></div>
        <div className="hero-content">
          <div className="hero-logo">
            <div className="logo-circle">
              <img src="/ok.png" alt="DSA Logo" className="hero-logo-img" />
            </div>
            <h1 className="hero-title">DSA Storyteller</h1>
            <p className="hero-subtitle">Learn Data Structures & Algorithms Through Stories</p>
          </div>
          
          <div className="hero-description">
            <p>Transform complex programming concepts into engaging narratives powered by AI</p>
          </div>

          <button className="cta-button" onClick={() => navigate('/login')}>
            <span className="cta-icon">🚀</span>
            <span className="cta-text">Enter the Realm</span>
            <span className="cta-arrow">→</span>
          </button>

          <div className="hero-stats">
            <div className="stat-item">
              <div className="stat-number">20+</div>
              <div className="stat-label">DSA Topics</div>
            </div>
            <div className="stat-item">
              <div className="stat-number">AI</div>
              <div className="stat-label">Powered Stories</div>
            </div>
            <div className="stat-item">
              <div className="stat-number">∞</div>
              <div className="stat-label">Learning Paths</div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="features-section">
        <div className="section-container">
          <h2 className="section-title">Why DSA Storyteller?</h2>
          <p className="section-subtitle">Revolutionary approach to learning programming</p>
          
          <div className="features-grid">
            {features.map((feature, index) => (
              <div className="feature-card" key={index}>
                <div className="feature-icon">{feature.icon}</div>
                <h3 className="feature-title">{feature.title}</h3>
                <p className="feature-description">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="how-it-works-section">
        <div className="section-container">
          <h2 className="section-title">How It Works</h2>
          <div className="steps-container">
            <div className="step-card">
              <div className="step-number">1</div>
              <h3>Choose Your Topic</h3>
              <p>Select from arrays, trees, graphs, sorting, and more</p>
            </div>
            <div className="step-arrow">→</div>
            <div className="step-card">
              <div className="step-number">2</div>
              <h3>Set Preferences</h3>
              <p>Pick your learning level and favorite story theme</p>
            </div>
            <div className="step-arrow">→</div>
            <div className="step-card">
              <div className="step-number">3</div>
              <h3>Learn & Practice</h3>
              <p>Read AI-generated stories, visualize, and take quizzes</p>
            </div>
          </div>
        </div>
      </section>

      {/* Team Section */}
      <section className="team-section">
        <div className="section-container">
          <h2 className="section-title">Meet Our Team</h2>
          <p className="section-subtitle">The minds behind DSA Storyteller</p>
          
          <div className="team-grid">
            {teamMembers.map((member, index) => (
              <div className="team-card" key={index}>
                <div className="team-avatar">
                  <img src={member.image} alt={member.name} className="team-avatar-img" />
                </div>
                <h3 className="team-name">{member.name}</h3>
                <p className="team-role">{member.role}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="final-cta-section">
        <div className="cta-content">
          <h2>Ready to Transform Your Learning?</h2>
          <p>Join thousands of students mastering DSA through stories</p>
          <button className="cta-button-large" onClick={() => navigate('/login')}>
            Start Your Journey Now
          </button>
        </div>
      </section>

      {/* Footer */}
      <footer className="landing-footer">
        <div className="footer-content">
          <div className="footer-logo">
            <img src="/ok.png" alt="DSA Logo" className="footer-logo-img" />
            <span className="logo-text">DSA Storyteller</span>
          </div>
          <p className="footer-text">
            Minor Project 2025<br />
            MBM University - 7th SEM - 2025
          </p>
        </div>
      </footer>
    </div>
  );
};

export default LandingPage;
